//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CamCal.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CAMCAL_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_GET_3D_DIALOG               132
#define IDD_CCD_PAR_DIALOG              133
#define IDR_MENU1                       138
#define IDR_MENU2                       139
#define IDC_STATIC_PARAMETERS           1015
#define IDC_LOAD_IMG                    1017
#define IDC_STATUS                      1018
#define IDC_STATIC_REF_POINT            1020
#define IDC_REF_POINT                   1021
#define IDC_CTR_X0                      1022
#define IDC_CTR_Y0                      1023
#define IDC_CTR_Z0                      1024
#define IDC_CTR_OMEGA                   1025
#define IDC_CTR_PHI                     1026
#define IDC_CAL_THRES                   1027
#define IDC_STATIC_CAL_THRES            1028
#define IDC_STATIC_X_0                  1029
#define IDC_STATIC_Y_0                  1030
#define IDC_STATIC_Z_0                  1031
#define IDC_STATIC_PHI                  1032
#define IDC_STATIC_KAPPA                1033
#define IDC_STATIC_OMEGA                1034
#define IDC_STATIC_XH                   1035
#define IDC_STATIC_YH                   1036
#define IDC_STATIC_S_X                  1037
#define IDC_STATIC_THETA                1038
#define IDC_STATIC_K1                   1039
#define IDC_STATIC_K2                   1040
#define IDC_STATIC_P1                   1041
#define IDC_STATIC_P2                   1042
#define IDC_CTR_KAPPA                   1043
#define IDC_CTR_FOCUS                   1044
#define IDC_CTR_XH                      1045
#define IDC_STATIC_FILE_CAM             1046
#define IDC_FILE_CALIB                  1047
#define IDC_CTR_YH                      1048
#define IDC_CTR_SX                      1049
#define IDC_CTR_THETA                   1050
#define IDC_CTR_K1                      1051
#define IDC_X_0                         1052
#define IDC_Y_0                         1053
#define IDC_Z_0                         1054
#define IDC_OMEGA                       1055
#define IDC_PHI                         1056
#define IDC_KAPPA                       1057
#define IDC_FOCUS                       1058
#define IDC_STATIC_FOCUS                1059
#define IDC_X_H                         1060
#define IDC_Y_H                         1061
#define IDC_S_X                         1062
#define IDC_THETA                       1063
#define IDC_K1                          1064
#define IDC_K2                          1065
#define IDC_P1                          1066
#define IDC_P2                          1067
#define IDC_SORT                        1068
#define IDC_CTR_K2                      1069
#define IDC_CTR_P1                      1070
#define IDC_CTR_P2                      1071
#define IDC_STATIC_FILE_CAL_IMG         1072
#define IDC_FILE_CAL_IMG                1073
#define IDC_STATIC_HISTO                1074
#define IDC_STATIC_AC                   1075
#define IDC_STATIC_GLOBAL_FILE          1076
#define IDC_FILE_GLOBAL                 1077
#define IDC_RMS                         1078
#define IDC_PLANE1                      1084
#define IDC_PLANE2                      1085
#define IDC_PLANE3                      1086
#define IDC_PLANE4                      1087
#define IDC_PLANE5                      1088
#define IDC_PLANE6                      1089
#define IDC_PLANE7                      1090
#define IDC_PLANE8                      1091
#define IDC_CAL_CAM                     1092
#define IDC_STATIC_RMS                  1093
#define IDC_PLANE9                      1094
#define IDC_PLANE10                     1095
#define IDC_PLANE0                      1097
#define IDC_DETECT                      1102
#define IDC_NEW_SET                     1103
#define IDC_STATIC_PLANES               1104
#define IDC_RESET_PARA                  1105
#define IDC_OPEN_CAL_IMAGE              1106
#define IDC_OPEN_GLOBAL_FILE            1107
#define IDC_LIN_CAL                     1110
#define IDC_PATH                        1111
#define IDC_DIR_PATH                    1112
#define IDC_STATIC_IMG_W                1114
#define IDC_STATIC_FILE_GLOBAL_W        1115
#define IDC_STATIC_HELP                 1116
#define IDC_GET_3D                      1118
#define IDC_FILE_STEREO_IMG1            1118
#define IDC_FILE_CAM1_PAR               1119
#define IDC_GET_LOOK_UP                 1119
#define IDC_DETECT_POINTS               1120
#define IDC_GET_EPI_3D_LIN              1121
#define IDC_STATIC_THRESHOLD            1122
#define IDC_THRESHOLD                   1123
#define IDC_FILE_STEREO_IMG2            1124
#define IDC_FILE_STEREO_IMG1_NAME       1125
#define IDC_FILE_CAM1_PAR_NAME          1126
#define IDC_STATIC_CAM1                 1127
#define IDC_STATIC_CAM2                 1128
#define IDC_FILE_STEREO_IMG2_NAME       1129
#define IDC_FILE_CAM2_PAR               1130
#define IDC_FILE_CAM2_PAR_NAME          1131
#define IDC_FILE_CCD1_PAR               1132
#define IDC_GET_EPI_3D2                 1132
#define IDC_GET_EPI_3D                  1132
#define IDC_CCD1_PAR_NAME               1133
#define IDC_FILE_STEREO_POS             1133
#define IDC_FILE_CCD2_PAR1              1134
#define IDC_FILE_STEREO_ANALYSE         1134
#define IDC_CCD2_PAR_NAME               1135
#define IDC_FILE_STEREO_EXP_POS         1135
#define IDC_OPEN_CCD_PAR_FILE           1136
#define IDC_IMAGE_HEIGHT                1137
#define IDC_ZMIN                        1137
#define IDC_STATIC_FILES                1138
#define IDC_IMAGE_WIDTH                 1138
#define IDC_ZMAX                        1138
#define IDC_PIXEL_HEIGHT                1139
#define IDC_TOLERANCE                   1139
#define IDC_STATIC_IMAGE_HEIGHT         1140
#define IDC_STATIC_IMAGE_WIDTH          1141
#define IDC_STATIC_PICEL_HEIGHT         1142
#define IDC_STATIC_PIXEL_WIDTH          1143
#define IDC_PIXEL_WIDTH                 1144
#define IDC_CCD1                        1144
#define IDC_CCD2                        1145
#define IDC_SHOW_IMAGES                 1146
#define IDC_STATIC_ZMIN                 1149
#define IDC_STATIC_ZMAX                 1150
#define IDC_STATIC_TOL                  1151
#define IDC_PROGRESS1                   1153
#define IDC_LIMITS                      1154
#define IDD_GAUSS                       32774
#define IDD_ROW_COR                     32775
#define IDD_MIN_SIZE                    32776
#define IDD_MAX_SIZE                    32777
#define ID_FILE_SAVENONLINCAMPAR        32778
#define ID_FILE_SAVELINEARCAMPAR        32779
#define ID_HELP_ABOUT                   32780
#define ID_CCDPARAMETERS_SET            32781
#define ID_FILE_CAMERA1IMAGE            32782
#define ID_FILE_CAMERA2IMAGE            32783
#define ID_FILE_CAMERA1PARAMETER        32784
#define ID_FILE_CAMERA2PARAMETER        32785
#define ID_CCD_CCD1PARAMETER            32787
#define ID_CCD_CCD2PARAMETER            32788
#define ID_FILE_CAMERA1REFIMAGE         32789
#define ID_FILE_CAMERA2REFIMAGE         32790
#define ID_IMAGEPROCESSING_SUBTRACTREFIMAGE 32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
